apiVersion: v1
name: rancher-vsphere-cpi
version: 1.0.0
appVersion: 1.0.0
description: vSphere Cloud Provider Interface (CPI)
sources:
  - https://github.com/kubernetes/cloud-provider-vsphere
icon: https://charts.rancher.io/assets/logos/vsphere-cpi.svg
maintainers:
  - name: Rancher
    email: caleb@rancher.com
keywords:
- infrastructure
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: kube-system
  catalog.cattle.io/release-name: vsphere-cpi
  catalog.cattle.io/display-name: "vSphere CPI"
  catalog.cattle.io/os: linux
