url: https://open-policy-agent.github.io/gatekeeper/charts/gatekeeper-3.7.1.tgz
version: 100.1.0
doNotRelease: true
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: crd-manifest
      addCRDValidationToMainChart: true
