annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: vSphere CPI
  catalog.cattle.io/namespace: kube-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: vsphere-cpi
apiVersion: v1
appVersion: 1.21.0
description: vSphere Cloud Provider Interface (CPI)
icon: https://charts.rancher.io/assets/logos/vsphere-cpi.svg
keywords:
- infrastructure
kubeVersion: 1.18 - 1.21
maintainers:
- email: caleb@rancher.com
  name: Rancher
name: rancher-vsphere-cpi
sources:
- https://github.com/kubernetes/cloud-provider-vsphere
version: 100.0.1
