annotations:
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/os: linux
  catalog.rancher.io/certified: rancher
  catalog.rancher.io/namespace: cattle-monitoring-system
  catalog.rancher.io/release-name: rancher-prometheus-adapter
  catalog.cattle.io/rancher-version: '>= 2.6.0-0 < 2.7.0-0'
  catalog.cattle.io/kube-version: '>= 1.16.0-0 < 1.22.0-0'
apiVersion: v1
appVersion: v0.8.4
description: A Helm chart for k8s prometheus adapter
home: https://github.com/DirectXMan12/k8s-prometheus-adapter
keywords:
- hpa
- metrics
- prometheus
- adapter
maintainers:
- email: mattias.gees@jetstack.io
  name: mattiasgees
- name: steven-sheehy
- email: hfernandez@mesosphere.com
  name: hectorj2f
name: rancher-prometheus-adapter
sources:
- https://github.com/kubernetes/charts
- https://github.com/DirectXMan12/k8s-prometheus-adapter
version: 100.0.0+up2.14.0
